# ===========================================================================
# NEON Plant Phenology Explorer — ui.R
# ===========================================================================
ui <- bslib::page_sidebar(
  theme = app_theme, title = NULL,
  window_title = "NEON Plant Phenology Explorer", fillable = FALSE,
  tags$head(
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = NA),
    tags$link(rel = "stylesheet", href = "https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700;800&display=swap"),
    tags$link(rel = "stylesheet", href = "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&display=swap"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/html-to-image@1.11.13/dist/html-to-image.js"),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("phe.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),
  sidebar = sidebar(
    width = 320, class = "control-deck",
    div(class = "brand", div(class = "brand-mark", "\U0001F33F"),
      div(div(class = "brand-title", "Plant Phenology Explorer"), div(class = "brand-sub", "NEON field observatory"))),
    selectInput("stateSel", label = tagList(bs_icon("geo-alt-fill"), " 1 · Pick a state"), choices = NULL, width = "100%"),
    selectInput("site", label = tagList(bs_icon("pin-map-fill"), " 2 · Pick a site"), choices = NULL, width = "100%"),
    uiOutput("siteBio"),
    actionButton("loadBtn", tagList(bs_icon("globe-americas"), " Explore this site"),
                 class = "btn-primary btn-lg w-100 load-btn", onclick = "smtLoadStart()"),
    actionButton("demoBtn", tagList(bs_icon("stars"), " or open the Harvard Forest demo (instant)"),
                 class = "btn-link btn-sm w-100 reset-demo", onclick = "smtLoadStart('Harvard Forest — demo dataset')"),
    hidden(div(id = "spPickerWrap", hr(class = "deck-hr"),
      selectizeInput("indSel", label = tagList(bs_icon("search"), " Open a plant's profile"), choices = NULL,
                     options = list(placeholder = "Pick a tagged plant…")),
      actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"), class = "btn-outline-dark btn-sm w-100"))),
    hr(class = "deck-hr"),
    actionButton("help", tagList(bs_icon("question-circle"), " How it works"), class = "btn-outline-dark btn-sm w-100"),
    div(class = "theme-toggle-row", tags$span(class = "theme-toggle-lab", bs_icon("circle-half"), " Theme"),
      input_dark_mode(id = "colorMode", mode = "light")),
    div(class = "deck-foot", bs_icon("database"), " NEON ", tags$code("DP1.10055.001"),
      br(), tags$a(href = "https://desertdatalabs.com", target = "_blank", bs_icon("box-arrow-up-right"), " Desert Data Labs"))
  ),
  div(id = "loadOverlay", class = "load-overlay", div(class = "load-card",
    div(class = "load-spin", "\U0001F331"), div(class = "load-title", "Loading site data"),
    div(id = "loadSite", class = "load-site"), div(class = "load-bar"),
    div(class = "load-note", "Building the phenology clock, onset board, and plant careers."))),
  uiOutput("heroStats"),
  div(id = "splash", div(class = "splash",
    div(class = "app-hero app-hero-splash",
      h1(class = "app-title", "NEON Plant Phenology Explorer", span(class = "title-tag", "unofficial")),
      p(class = "app-subtitle", "When the leaves break, the flowers open, and the canopy turns — every tagged plant NEON watches at a site, week by week, year after year. Built on twice-weekly phenophase observations (DP1.10055.001).")),
    p("Tap a site on the map — ", tags$b("bigger dots"), " carry more tagged plants, ", tags$b("color"), " is median green-up (green = early spring, amber = late). Or jump straight to one, or open the demo."),
    div(class = "picker-actions", style = "margin:6px 0 12px",
      div(style = "min-width:260px; flex:1 1 380px; max-width:440px",
        selectizeInput("siteSearch", NULL, choices = NULL, width = "100%",
          options = list(placeholder = "Jump to a site by code, name, or state…")))),
    div(class = "picker-map-wrap", leafletOutput("nationalMap", height = "460px")),
    div(class = "picker-map-hint", bs_icon("hand-index-thumb"), " tap a dot, then ", tags$b("Explore this site"), " — or pick by state in the sidebar"),
    div(class = "picker-actions", actionButton("demoBtn2", tagList(bs_icon("stars"), " Open the Harvard Forest demo instantly"),
      class = "btn-primary btn-lg", onclick = "smtLoadStart('Harvard Forest — demo dataset')")))),
  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    navset_card_tab(id = "tabs",
      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        div(class = "home-nav",
          actionButton("goClock", tagList(bs_icon("clock-history"), div("Phenology Clock"), tags$small("the year, week by week")), class = "home-btn home-btn-star"),
          actionButton("goOnset", tagList(bs_icon("bullseye"), div("Onset Lab"), tags$small("every plant, pinnable")), class = "home-btn"),
          actionButton("goProfile", tagList(bs_icon("flower1"), div("Plant Profile"), tags$small("one plant's career")), class = "home-btn"),
          actionButton("goMap", tagList(bs_icon("map-fill"), div("Map"), tags$small("plots across the site")), class = "home-btn")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "What's tagged here",
            info_pop("Growth forms",
              p("The tagged plants at this site, grouped by ", tags$b("growth form"), " — deciduous broadleaf trees, evergreen conifers, forbs, and so on. Each is watched for the phenophases its growth form shows."),
              p(class="caveat", bs_icon("exclamation-triangle"), " Phenology is monitored on a ", tags$b("fixed roster of tagged individuals"), " along transects — it is a within-site timing signal, not a site-wide census of abundance."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("formBar", height = "380px"))),
        card(card_head("stars", "The story so far", info_pop("Story", p("Written from this site's live data."))),
          uiOutput("siteInsights")),
        card(card_head("download", "Take the data with you",
          info_pop("Analysis-ready export",
            p("A zip of tidy CSVs — the long observation table, per-plant-year onsets (with a ", tags$b("left-censored"), " flag), per-plant summaries, the weekly clock table, and the species green-up trend — plus a ", tags$b("codebook"), " decoding every column, the phenophases, and the methods."),
            p(class="caveat", bs_icon("check-circle"), " Built to load straight into R or Python; documented so it's still usable in five years."))),
          div(style = "padding:2px 2px 4px",
            p(style = "color:var(--muted);font-size:13.5px;margin-bottom:10px",
              "Everything this site computes, as documented CSVs you can analyze yourself."),
            downloadButton("siteBundle", "Download analysis bundle (CSV + codebook)", class = "btn-primary")))),

      nav_panel(title = tagList(bs_icon("clock-history"), " Phenology Clock"), value = "clock",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("The year, week by week",
             info_pop("Phenology Clock",
               p("Each colored arc is a ", tags$b("phenophase"), " — breaking leaf buds, leaves, open flowers, colored leaves, falling leaves. The further the arc reaches out from the center in a given week, the larger the ", tags$b("share of plants"), " in that phenophase that week."),
               p("Read it like a clock of the year: where the green arcs peak is leaf-out; where the pink peaks is bloom; where the orange peaks is autumn."),
               p(class="caveat", bs_icon("exclamation-triangle"), " This view ", tags$b("pools all monitored years"), " to show the typical season — use the Onset Lab to see year-to-year shifts."))),
          p("The typical seasonal cycle of every phenophase, pooled across years. Switch species to compare how different plants time their year.")),
          div(class = "sizelab-controls",
            selectInput("clockSp", tagList(bs_icon("flower2"), " Species"),
                        choices = c("All species" = ""), selected = "", width = "300px"))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("clock-history", "Phenophase clock (share of plants 'yes', by week)",
              info_pop("Reading the clock", p("Angle = week of the year (Jan at the top, moving clockwise). Radius = % of monitored plants recorded in that phenophase that week."))),
            spin(plotlyOutput("clockPlot", height = "470px"))),
          card(full_screen = TRUE,
            card_head("graph-down-arrow", "Is green-up shifting?",
              info_pop("Onset trend", p("Median ", tags$b("green-up onset"), " (first leaf-out, day-of-year) per year, across plants of each species. A downward slope means spring is arriving earlier; points need ", tags$b("≥3 plants"), " in a species-year to show."))),
            uiOutput("trendInsight"), spin(plotlyOutput("trendPlot", height = "360px"))))),

      nav_panel(title = tagList(bs_icon("bullseye"), " Onset Lab"), value = "onset",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Every plant on one board",
             info_pop("Onset Lab",
               p("Each dot is a ", tags$b("tagged plant"), ", placed by its ", tags$b("green-up onset"), " (median day-of-year it first breaks leaf) and its ", tags$b("leaf-active days"), " (how many days a year it actually carries leaves — counted week by week, so a desert plant that flushes twice with the rains isn't credited a 300-day season)."),
               p(tags$b("Tap a dot"), " to pin its card; tap “Open plant profile” for its full phenophase career. Faint dots don't yet have both leaf-out and leaf-active days recorded."))),
          p("Each dot is a plant — when it wakes × how many days it carries leaves. Tap to pin a card; open any plant's full career.")),
          div(class = "sizelab-controls",
            selectInput("onsetColor", tagList(bs_icon("palette"), " Colour by"),
                        choices = c("Growth form" = "growthForm", "Species" = "scientificName", "Native status" = "nativeStatusCode"),
                        selected = "growthForm", width = "200px"))),
        card(full_screen = TRUE,
          card_head("bullseye", "Green-up onset × leaf-active days, by plant",
            info_pop("Reading this", p("Left = early risers (wake early in spring); right = late sleepers. High = carries leaves many days a year; low = brief. The ", tags$span(style="color:#d98014;font-weight:700","amber diamond"), " is the plant you're viewing."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveScatter()", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          uiOutput("onsetCoverage"),
          div(class = "smt-pinnable", spin(plotlyOutput("onsetBoard", height = "560px")))),
        uiOutput("indCardSlot")),

      nav_panel(title = tagList(bs_icon("flower1"), " Plant Profile"), value = "profile", uiOutput("plantProfile")),

      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Phenology plots across the site"),
          p("Each marker is a NEON phenology plot, sized by how many plants are tagged there and coloured by your chosen metric.")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "210px", choices = c("Median green-up (DOY)" = "greenup", "Leaf-active days (desert-safe)" = "leaf_active", "Plants tagged" = "n_ind")),
            selectInput("view", "Basemap", width = "160px", choices = c("Light" = "CartoDB.Positron", "Terrain" = "Esri.WorldTopoMap", "Satellite" = "Esri.WorldImagery")))),
        uiOutput("mapCoverage"),
        card(full_screen = TRUE, spin(leafletOutput("map", height = "620px")))),

      nav_panel(title = tagList(bs_icon("globe-americas"), " Across sites"), value = "cross",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Green-up across the network",
             info_pop("Cross-site gradient",
               p("Each point is a ", tags$b("bundled site"), ", placed by its latitude and its median green-up day pooled across all its species. The dashed line is the fit."),
               p(class="caveat", bs_icon("exclamation-triangle"), " Sites differ in which species they monitor, so this is a ", tags$b("gradient across the network"), " — the spatial echo of Hopkins' bioclimatic law, not a controlled experiment. The banner leads with the ", tags$b("within-species"), " slope (species held constant), which removes that confound."),
               p(class="caveat", bs_icon("clock-history"), " Sites also differ in ", tags$b("visit cadence"), ": onset is interval-censored to the gap between visits, so part of an onset difference between two sites can be censoring geometry, not plant biology — read across-site differences as approximate."))),
          p("Move north and up in elevation, and spring arrives later — the same signal climate change shifts in time, laid out here in space."))),
        uiOutput("gradientInsight"),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE, card_head("graph-up-arrow", "Median green-up vs latitude"),
            spin(plotlyOutput("gradientPlot", height = "460px"))),
          card(full_screen = TRUE, card_head("signpost-split", "The same species, across its range",
            info_pop("Same species across sites", p("For a species monitored at several sites, its median green-up day at each — a cleaner read on the gradient because the species is held constant (≥3 plants per site)."))),
            div(class = "sizelab-controls", style = "margin-bottom:8px",
              selectInput("xsSpecies", tagList(bs_icon("flower2"), " Species (≥2 sites)"), choices = NULL, width = "100%")),
            spin(plotlyOutput("speciesAcrossPlot", height = "380px"))))),

      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about", uiOutput("aboutPanel"))
    )),
  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta", href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Plant%20Phenology%20Explorer",
      span(class = "hand", "\U0001F44B"), "Want a custom data app like this for your project?")),
    p(style = "margin-top:12px", HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · feedback or custom dashboards → "),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Plant%20Phenology%20Explorer", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85", "Data: NEON Plant Phenology Observations (DP1.10055.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
