# ===========================================================================
# NEON Plant Phenology Explorer — ui.R
# ===========================================================================
ui <- bslib::page_sidebar(
  theme = app_theme, title = NULL,
  window_title = "NEON Plant Phenology Explorer", fillable = FALSE,
  tags$head(
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = NA),
    tags$link(rel = "stylesheet", href = "https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700;800&display=swap"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.2/dist/confetti.browser.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/html-to-image@1.11.13/dist/html-to-image.js"),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("phe.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),
  sidebar = sidebar(
    width = 320, class = "control-deck",
    div(class = "brand", div(class = "brand-mark", "\U0001F33F"),
      div(div(class = "brand-title", "Plant Phenology Explorer"), div(class = "brand-sub", "NEON field observatory"))),
    selectInput("stateSel", label = tagList(bs_icon("geo-alt-fill"), " 1 · Pick a state"), choices = NULL, width = "100%"),
    selectInput("site", label = tagList(bs_icon("pin-map-fill"), " 2 · Pick a site"), choices = NULL, width = "100%"),
    uiOutput("siteBio"),
    actionButton("loadBtn", tagList(bs_icon("globe-americas"), " Explore this site"),
                 class = "btn-primary btn-lg w-100 load-btn", onclick = "smtLoadStart()"),
    actionButton("demoBtn", tagList(bs_icon("stars"), " or open the Harvard Forest demo (instant)"),
                 class = "btn-link btn-sm w-100 reset-demo", onclick = "smtLoadStart('Harvard Forest — demo dataset')"),
    hidden(div(id = "spPickerWrap", hr(class = "deck-hr"),
      selectizeInput("indSel", label = tagList(bs_icon("search"), " Open a plant's profile"), choices = NULL,
                     options = list(placeholder = "Pick a tagged plant…")),
      actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"), class = "btn-outline-dark btn-sm w-100"))),
    hr(class = "deck-hr"),
    actionButton("help", tagList(bs_icon("question-circle"), " How it works"), class = "btn-outline-dark btn-sm w-100"),
    div(class = "theme-toggle-row", tags$span(class = "theme-toggle-lab", bs_icon("circle-half"), " Theme"),
      input_dark_mode(id = "colorMode", mode = "light")),
    div(class = "deck-foot", bs_icon("database"), " NEON ", tags$code("DP1.10055.001"),
      br(), tags$a(href = "https://desertdatalabs.com", target = "_blank", bs_icon("box-arrow-up-right"), " Desert Data Labs"))
  ),
  div(id = "loadOverlay", class = "load-overlay", div(class = "load-card",
    div(class = "load-spin", "\U0001F331"), div(class = "load-title", "Loading site data"),
    div(id = "loadSite", class = "load-site"), div(class = "load-bar"),
    div(class = "load-note", "Building the phenology clock, onset board, and plant careers."))),
  uiOutput("heroStats"),
  div(id = "splash", div(class = "splash",
    div(class = "app-hero app-hero-splash",
      h1(class = "app-title", "NEON Plant Phenology Explorer", span(class = "title-tag", "unofficial")),
      p(class = "app-subtitle", "When the leaves break, the flowers open, and the canopy turns — every tagged plant NEON watches at a site, week by week, year after year. Built on twice-weekly phenophase observations (DP1.10055.001).")),
    p("Pick a ", tags$b("site"), " below, or open the Harvard Forest demo — red maple, red oak, and a New England forest waking each spring."),
    uiOutput("siteCards"),
    div(class = "picker-actions", actionButton("demoBtn2", tagList(bs_icon("stars"), " Open the Harvard Forest demo instantly"),
      class = "btn-primary btn-lg", onclick = "smtLoadStart('Harvard Forest — demo dataset')")))),
  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    navset_card_tab(id = "tabs",
      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        div(class = "home-nav",
          actionButton("goClock", tagList(bs_icon("clock-history"), div("Phenology Clock"), tags$small("the year, week by week")), class = "home-btn home-btn-star"),
          actionButton("goOnset", tagList(bs_icon("bullseye"), div("Onset Lab"), tags$small("every plant, pinnable")), class = "home-btn"),
          actionButton("goProfile", tagList(bs_icon("flower1"), div("Plant Profile"), tags$small("one plant's career")), class = "home-btn"),
          actionButton("goMap", tagList(bs_icon("map-fill"), div("Map"), tags$small("plots across the site")), class = "home-btn")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "What's tagged here",
            info_pop("Growth forms",
              p("The tagged plants at this site, grouped by ", tags$b("growth form"), " — deciduous broadleaf trees, evergreen conifers, forbs, and so on. Each is watched for the phenophases its growth form shows."),
              p(class="caveat", bs_icon("exclamation-triangle"), " Phenology is monitored on a ", tags$b("fixed roster of tagged individuals"), " along transects — it is a within-site timing signal, not a site-wide census of abundance."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("formBar", height = "380px"))),
        card(card_head("stars", "The story so far", info_pop("Story", p("Written from this site's live data."))),
          uiOutput("siteInsights"))),

      nav_panel(title = tagList(bs_icon("clock-history"), " Phenology Clock"), value = "clock",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("The year, week by week",
             info_pop("Phenology Clock",
               p("Each colored arc is a ", tags$b("phenophase"), " — breaking leaf buds, leaves, open flowers, colored leaves, falling leaves. The further the arc reaches out from the center in a given week, the larger the ", tags$b("share of plants"), " in that phenophase that week."),
               p("Read it like a clock of the year: where the green arcs peak is leaf-out; where the pink peaks is bloom; where the orange peaks is autumn."),
               p(class="caveat", bs_icon("exclamation-triangle"), " This view ", tags$b("pools all monitored years"), " to show the typical season — use the Onset Lab to see year-to-year shifts."))),
          p("The typical seasonal cycle of every phenophase, pooled across years. Switch species to compare how different plants time their year.")),
          div(class = "sizelab-controls",
            selectInput("clockSp", tagList(bs_icon("flower2"), " Species"),
                        choices = c("All species" = ""), selected = "", width = "300px"))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("clock-history", "Phenophase clock (share of plants 'yes', by week)",
              info_pop("Reading the clock", p("Angle = week of the year (Jan at the top, moving clockwise). Radius = % of monitored plants recorded in that phenophase that week."))),
            spin(plotlyOutput("clockPlot", height = "470px"))),
          card(full_screen = TRUE,
            card_head("graph-down-arrow", "Is green-up shifting?",
              info_pop("Onset trend", p("Median ", tags$b("green-up onset"), " (first leaf-out, day-of-year) per year, across plants of each species. A downward slope means spring is arriving earlier; points need ", tags$b("≥3 plants"), " in a species-year to show."))),
            uiOutput("trendInsight"), spin(plotlyOutput("trendPlot", height = "360px"))))),

      nav_panel(title = tagList(bs_icon("bullseye"), " Onset Lab"), value = "onset",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Every plant on one board",
             info_pop("Onset Lab",
               p("Each dot is a ", tags$b("tagged plant"), ", placed by its ", tags$b("green-up onset"), " (median day-of-year it first breaks leaf) and its ", tags$b("growing-season length"), " (green-up to leaf-off — the last day leaves are present)."),
               p(tags$b("Tap a dot"), " to pin its card; tap “Open plant profile” for its full phenophase career. Faint dots don't yet have both leaf-out and leaf-off recorded."))),
          p("Each dot is a plant — when it wakes × how long its season runs. Tap to pin a card; open any plant's full career.")),
          div(class = "sizelab-controls",
            selectInput("onsetColor", tagList(bs_icon("palette"), " Colour by"),
                        choices = c("Growth form" = "growthForm", "Species" = "scientificName", "Native status" = "nativeStatusCode"),
                        selected = "growthForm", width = "200px"))),
        card(full_screen = TRUE,
          card_head("bullseye", "Green-up onset × season length, by plant",
            info_pop("Reading this", p("Left = early risers (wake early in spring); right = late sleepers. High = long growing season; low = short. The ", tags$span(style="color:#c9a300;font-weight:700","gold diamond"), " is the plant you're viewing."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveScatter()", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", spin(plotlyOutput("onsetBoard", height = "560px")))),
        uiOutput("indCardSlot")),

      nav_panel(title = tagList(bs_icon("flower1"), " Plant Profile"), value = "profile", uiOutput("plantProfile")),

      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Phenology plots across the site"),
          p("Each marker is a NEON phenology plot, sized by how many plants are tagged there and coloured by your chosen metric.")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "190px", choices = c("Median green-up (DOY)" = "greenup", "Plants tagged" = "n_ind")),
            selectInput("view", "Basemap", width = "160px", choices = c("Satellite" = "Esri.WorldImagery", "Terrain" = "Esri.WorldTopoMap", "Light" = "CartoDB.Positron")))),
        spin(leafletOutput("map", height = "620px"))),
      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about", uiOutput("aboutPanel"))
    )),
  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta", href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Plant%20Phenology%20Explorer",
      span(class = "hand", "\U0001F44B"), "Want a custom data app like this for your project?")),
    p(style = "margin-top:12px", HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · feedback or custom dashboards → "),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Plant%20Phenology%20Explorer", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85", "Data: NEON Plant Phenology Observations (DP1.10055.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
